name: SevsWarden
main: be.seveningful.sw.SevsWarden
version: SNAP_1a27b
author: Seveningful
depend:
  - ProtocolLib
description: 'Le Warden de Seveningful'

permissions:
   sw.immune:
     description: Bypass anti-cheat
     permission: sw.immune
   sw.check.forcefield:
     description: Donne acces a la commande /sw ff [joueur]
     permission: sw.check.forcefield
   sw.reset:
     description: Donne acces a la commande /sw reset <joueur>
     permission: sw.reset
     

commands:
  sw:
    usage: /sw
    description: Commande pricipale du plugin